title: LeakLense Docs
description: Documentation for LeakLense

remote_theme: just-the-docs/just-the-docs

url: "https://dr-gecko.github.io"
baseurl: "/LeakLense"

permalink: pretty

plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap

search_enabled: true
enable_copy_code_button: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "LeakLense on GitHub":
  - "https://github.com/dr-gecko/LeakLense"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/dr-gecko/LeakLense"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: nil

defaults:
- scope:
    path: "docs"
    type: "pages"
  values:
    layout: "default"

exclude:
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/
