services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ${PWD}/../web_data/frontend:/usr/share/nginx/html
      - user-avatars:/usr/share/nginx/html/static/avatars/useruploaded
      - ${PWD}/../data/logs/:/var/log/nginx
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ${PWD}/../web_data/backend/
    container_name: fastapi_server
    ports:
      - "8081:8080"
    volumes:
      - ${PWD}/../web_data/backend/server:/app
      - user-avatars:/app/avatars
    working_dir: /app
    environment:
      mysql_host: ${mysql_host}
      sql_port: ${mysql_port}
      mysql_user: ${mysql_user}
      mysql_password: ${mysql_password}
      mysql_db: breaches
      mysql_backend_db: backend
      SHARED_PUBLIC_DIR: /app/avatars
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: breaches
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
    volumes:
      - ${PWD}/../data/mariadb:/var/lib/mysql
      - ${PWD}/mariadb-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
volumes:
  user-avatars: